name: Build ESP32-C3 MicroPython
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: "v5.3"
      - name: Install ESP-IDF tools & build
        run: |
          . /tmp/esp/idf/v5.3/esp-idf/install.sh
          . /tmp/esp/idf/v5.3/esp-idf/export.sh
          cd ports/esp32
          idf.py set-target esp32c3
          idf.py build
